{% set name = "codepy" %}
{% set version = "2023.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/codepy-{{ version }}.tar.gz
  sha256: bce2e136e9fb3cf59949427d4ef419648778401e6db288596e75b53e144f8b93

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - appdirs >=1.4.0
    - cgen
    - numpy >=1.6
    - python >={{ python_min }}
    - pytools >=2015.1.2
    - six

test:
  imports:
    - codepy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://mathema.tician.de/software/codepy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate and execute native code at run time, from Python
  description: |
    CodePy is a C/C++ metaprogramming toolkit for Python. It helps you
    compile source code and dynamically load it into the Python
    interpreter. This facility also works in conjunction with with
    PyCuda. Dynamic compilation and linking are so far only supported
    in Linux with the GNU toolchain.
  doc_url: http://mathema.tician.de/software/codepy
  dev_url: https://github.com/inducer/codepy

extra:
  recipe-maintainers:
    - inducer
    - jan-janssen
